services:
  mongo:
    image: mongo:latest
    container_name: safar_punjab_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: safar_punjab_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build: .
    container_name: safar_punjab_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DATABASE_NAME=safar_punjab
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongo
      - redis

  worker:
    build: .
    container_name: safar_punjab_worker
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DATABASE_NAME=safar_punjab
    command: celery -A celery_worker.celery_app worker --loglevel=info
    depends_on:
      - redis

volumes:
  mongo-data: